# GoReleaser configuration for xatu-sidecar
# This builds shared libraries for Linux platforms (amd64 and arm64)
#
# Note: Cross-compilation requires appropriate C compilers:
# - Linux ARM64: aarch64-linux-gnu-gcc
#
# To build for all architectures, install the required cross-compiler or use Docker

project_name: xatu-sidecar

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: xatu-sidecar-linux
    main: .
    binary: libxatu
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    
    
    buildmode: c-shared
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/ethpandaops/xatu-sidecar/pkg/version.version={{.Version}}
      - -X github.com/ethpandaops/xatu-sidecar/pkg/version.commit={{.Commit}}
      - -X github.com/ethpandaops/xatu-sidecar/pkg/version.date={{.Date}}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc
          - CXX=aarch64-linux-gnu-g++
          - CGO_ENABLED=1


archives:
  - id: shared-libs
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    
    # Archive name template
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    
    # Include only the built library and header file
    files:
      - src: libxatu.h
        dst: libxatu.h
    
    # Platform-specific naming is handled in name_template

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: 'Features'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# GitHub Release
release:
  github:
    owner: ethpandaops  # Update this
    name: xatu-sidecar   # Update this
  
  # Release notes
  header: |
    ## xatu-sidecar v{{ .Version }}
    
    Embeddable beacon chain event streaming library for Ethereum consensus clients (Linux only).
    
    ### Installation
    
    Download the appropriate shared library for your platform and architecture:
    - Linux AMD64: `libxatu.so`
    - Linux ARM64: `libxatu.so`
    
    Include the `libxatu.h` header file in your project.
  
  footer: |
    ## Verifying checksums
    
    ```bash
    sha256sum -c checksums.txt
    ```
    
    ## Integration
    
    See the [README](https://github.com/ethpandaops/xatu-sidecar#readme) for integration instructions.
  
  # Mark as prerelease for alpha/beta versions
  prerelease: auto
  
  # Create draft release first
  draft: false

# No additional configuration needed - header file is included in archives